import './main-v9'

type ShadowResult={status:'idle'|'shadowing'|'promoted'|'rejected';evaluated:number;challengerWins:number;championWins:number;ties:number;championLoss:number;challengerLoss:number;improvement:number;reason:string;at:number}
type ShadowState={challenger:Record<string,number>|null;sourceCycle:number;samples:Array<unknown>;promoted:number;rejected:number;last:ShadowResult}
type ReflectionState={buffer:Array<unknown>;cycles:number;accepted:number;rejected:number;last?:{reason?:string}}
type DecisionShadowResult={status:'idle'|'shadowing'|'promoted'|'rejected';evaluated:number;agreements:number;divergences:number;supportedDivergences:number;avgEstimatedGain:number;reason:string;at:number}
type DecisionShadowSample={championLabel:string;challengerLabel:string;agreed:boolean;supported:boolean;estimatedGain:number;confidence:number}
type DecisionShadowState={samples:DecisionShadowSample[];actionValues:Record<string,{count:number;avgReward:number}>;last:DecisionShadowResult}
type StoredStrategy={updates?:number;avgReward?:number;reflection?:ReflectionState;shadow?:ShadowState;decisionShadow?:DecisionShadowState}
type StoredWorld={strategy?:StoredStrategy}

const STORAGE_KEY='tiny-world-v9-strategy-v1'
const panel=document.querySelector<HTMLElement>('#brainPanel')
let observer:MutationObserver|undefined
let decorating=false
function readStrategy():StoredStrategy|null{try{return(JSON.parse(localStorage.getItem(STORAGE_KEY)??'{}')as StoredWorld).strategy??null}catch{return null}}
function pct(v:number){return`${(Math.max(-1,Math.min(1,v))*100).toFixed(2)}%`}
function reflectionMini(s:StoredStrategy|null){const r=s?.reflection;if(!r)return'';return`<div class="reflection-mini"><span>离线反思 ${r.cycles??0}</span><span>通过 ${r.accepted??0}</span><span>拒绝 ${r.rejected??0}</span><span>回放池 ${r.buffer?.length??0}/8</span></div>`}
function shadowMarkup(s:StoredStrategy|null){const sh=s?.shadow;if(!sh)return`<div class="shadow-card"><div class="shadow-head"><b>价值影子</b><span>等待 Challenger</span></div><p>Champion 控制真实行为；Challenger 只预测已执行动作的真实回报。</p></div>`;const last=sh.last??{status:'idle',evaluated:0,challengerWins:0,championWins:0,ties:0,championLoss:0,challengerLoss:0,improvement:0,reason:'等待 Challenger',at:Date.now()},active=Boolean(sh.challenger),state=last.status==='promoted'?'✓ 已晋升':last.status==='rejected'?'× 已淘汰':active?`◌ ${last.evaluated}/10`:'… 等待下一轮',losses=last.evaluated?`Champion ${last.championLoss.toFixed(3)} · Challenger ${last.challengerLoss.toFixed(3)} · 改善 ${pct(last.improvement)}`:'尚无价值影子结果';return`<div class="shadow-card ${last.status}"><div class="shadow-head"><b>价值影子</b><span>${state}</span></div><div class="shadow-score"><span>Challenger 胜 <b>${last.challengerWins}</b></span><span>Champion 胜 <b>${last.championWins}</b></span><span>平 <b>${last.ties}</b></span></div><div class="shadow-loss">${losses}</div><p>${last.reason}</p><small>累计晋升 ${sh.promoted??0} · 淘汰 ${sh.rejected??0} · 来源反思 #${sh.sourceCycle??0}</small></div>`}
function decisionMarkup(s:StoredStrategy|null){const ds=s?.decisionShadow;if(!ds)return`<div class="decision-shadow-card"><div class="decision-shadow-head"><b>策略决策影子</b><span>等待候选集</span></div><p>每次 Planner 的候选动作会被记录，Challenger 在同一状态下重新选 Top-1。</p></div>`;const last=ds.last??{status:'idle',evaluated:0,agreements:0,divergences:0,supportedDivergences:0,avgEstimatedGain:0,reason:'等待策略决策样本',at:Date.now()},recent=ds.samples?.slice(-3)??[],pairs=recent.map(x=>x.agreed?`=${x.championLabel}`:`${x.championLabel} → ${x.challengerLabel}${x.supported?'':' ?'}`).join(' · ')||'暂无 Top-1 对照',evidence=Object.values(ds.actionValues??{}).filter(x=>x.count>=2).length;return`<div class="decision-shadow-card ${last.status}"><div class="decision-shadow-head"><b>策略决策影子</b><span>${last.status==='promoted'?'✓ 决策门通过':last.status==='rejected'?'× 决策门未通过':`Top-1 对照 ${last.evaluated}/10`}</span></div><div class="decision-shadow-score"><span>一致 <b>${last.agreements}</b></span><span>分歧 <b>${last.divergences}</b></span><span>有证据 <b>${last.supportedDivergences}</b></span></div><div class="decision-shadow-gain">替代动作平均反事实估计增益 <b>${pct(last.avgEstimatedGain)}</b></div><p>${last.reason}</p><small>${pairs}</small><em>已有 ${evidence} 类动作具备 ≥2 次真实历史，可用于反事实估计</em></div>`}
function decorate(){if(!panel||decorating)return;decorating=true;observer?.disconnect();const s=readStrategy(),title=panel.querySelector<HTMLElement>('.brain-title b'),meta=panel.querySelector<HTMLElement>('.brain-title span');if(title)title.textContent='双重影子评估 V12';if(meta){const sh=s?.shadow,ds=s?.decisionShadow;meta.textContent=sh?.challenger?`Challenger 运行中 · Top-1 分歧 ${ds?.last?.divergences??0}`:`Champion 控制中 · 晋升 ${sh?.promoted??0} / 淘汰 ${sh?.rejected??0}`};panel.querySelector('.v10-reflection')?.remove();panel.querySelector('.shadow-card')?.remove();panel.querySelector('.reflection-mini')?.remove();panel.querySelector('.decision-shadow-card')?.remove();const strategyCard=panel.querySelector('.strategy-card');const html=reflectionMini(s)+shadowMarkup(s)+decisionMarkup(s);if(strategyCard)strategyCard.insertAdjacentHTML('afterend',html);else panel.insertAdjacentHTML('afterbegin',html);observer?.observe(panel,{childList:true,subtree:true});decorating=false}
if(panel){observer=new MutationObserver(decorate);observer.observe(panel,{childList:true,subtree:true});decorate()}
const status=document.querySelector<HTMLElement>('#statusText'),badge=document.querySelector<HTMLElement>('#autoBadge')
if(status)status.textContent='Champion 控制真实行为；Challenger 同时做价值预测和 Top-1 决策影子，两道门都通过才晋升'
if(badge)badge.textContent='双重影子评估中'
