import * as THREE from 'three'
import {OrbitControls} from 'three/addons/controls/OrbitControls.js'
import {createStrategy,toyStrategyScore,socialStrategyScore} from './strategy-v9'
import type {StrategyFeatures} from './strategy-v16'

const $=<T extends Element>(s:string)=>document.querySelector<T>(s)!
const canvas=$<HTMLCanvasElement>('#scene'),status=$<HTMLElement>('#statusText'),toyGrid=$<HTMLElement>('#toyGrid'),brain=$<HTMLElement>('#brain'),toast=$<HTMLElement>('#toast')
const cinema=$<HTMLButtonElement>('#cinemaButton'),day=$<HTMLButtonElement>('#dayButton'),pause=$<HTMLButtonElement>('#pauseButton'),reset=$<HTMLButtonElement>('#resetButton')
const clamp01=(v:number)=>Math.max(0,Math.min(1,v)),C={sand:0xe7d5b8,white:0xfffaf0,peach:0xef9b7e,coral:0xdd7865,butter:0xefca72,mint:0xa9cfbe,sky:0x9ebed2,lavender:0xb8a9ca,cocoa:0x896b58,pink:0xef92aa,dark:0x493d37}
const scene=new THREE.Scene();scene.background=new THREE.Color(0xf0e4cf);scene.fog=new THREE.Fog(0xf0e4cf,17,33)
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'default'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,60),cameraHome=new THREE.Vector3(11,8.4,13);camera.position.copy(cameraHome)
const controls=new OrbitControls(camera,canvas);controls.target.set(0,1,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=24;controls.maxPolarAngle=Math.PI*.49;controls.autoRotate=true;controls.autoRotateSpeed=.24;controls.update()
const hemi=new THREE.HemisphereLight(0xfff7e7,0x889698,2.5),sun=new THREE.DirectionalLight(0xffdfb7,3.8);sun.position.set(-6,10,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=10;sun.shadow.camera.bottom=-10;scene.add(hemi,sun)
const mat=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:.8,metalness:0}),box=(w:number,h:number,d:number,color:number)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.castShadow=true;m.receiveShadow=true;return m},sphere=(r:number,color:number)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(r,20,16),mat(color));m.castShadow=true;m.receiveShadow=true;return m}
const world=new THREE.Group();scene.add(world);const floor=box(13,.35,11,C.sand);floor.position.y=-.25;world.add(floor)
for(let x=-3;x<=3;x++)for(let z=-2;z<=2;z++){const colors=[C.peach,C.butter,C.mint,C.sky,C.lavender],t=box(1.48,.08,1.48,colors[(x+z+20)%colors.length]);t.position.set(x*1.48,.01,z*1.48+.25);world.add(t)}
const back=box(13,5.3,.25,C.white),left=box(.25,5.3,11,C.white);back.position.set(0,2.4,-5.5);left.position.set(-6.5,2.4,0);world.add(back,left)
const windowSky=new THREE.Mesh(new THREE.PlaneGeometry(3.4,2.1),new THREE.MeshBasicMaterial({color:0x9ccfea}));windowSky.position.set(-2.6,3.25,-5.35);world.add(windowSky);const frameH=box(3.6,.09,.08,C.white),frameV=box(.09,2.3,.08,C.white);frameH.position.set(-2.6,3.25,-5.2);frameV.position.set(-2.6,3.25,-5.2);world.add(frameH,frameV)
const couch=new THREE.Group();const seat=box(2.5,.55,1.3,C.lavender),cb=box(2.5,1.15,.42,0xaa9ac0);seat.position.y=.45;cb.position.set(0,1,-.45);couch.add(seat,cb);couch.position.set(4.2,0,2.55);world.add(couch)
const shelf=box(3.1,1.35,.75,0xd2ad82);shelf.position.set(3.8,.68,-5.02);world.add(shelf)
const castle=new THREE.Group();for(const x of[-.8,.8]){const tower=box(.7,2,.7,x<0?C.peach:C.sky);tower.position.set(x,1,0);castle.add(tower);const roof=new THREE.Mesh(new THREE.ConeGeometry(.52,.72,4),mat(x<0?C.coral:0x7399b0));roof.rotation.y=Math.PI/4;roof.position.set(x,2.35,0);castle.add(roof)}const bridge=box(1.25,.18,.7,C.mint);bridge.position.y=1.7;castle.add(bridge);castle.position.set(-4.15,.05,-3.35);world.add(castle)

type Toy={key:string;label:string;emoji:string;position:THREE.Vector3;group:THREE.Group}
const toys:Toy[]=[]
function addToy(key:string,label:string,emoji:string,position:THREE.Vector3,group:THREE.Group){group.position.copy(position);world.add(group);toys.push({key,label,emoji,position,group})}
const blocks=new THREE.Group();[[-.45,.25,0,C.coral],[.05,.25,.05,C.butter],[.5,.25,0,C.sky],[-.18,.7,.03,C.mint],[.3,.7,.02,C.lavender]].forEach(([x,y,z,c])=>{const b=box(.45,.45,.45,c as number);b.position.set(x as number,y as number,z as number);blocks.add(b)});addToy('blocks','积木','▦',new THREE.Vector3(-3.5,.05,2.65),blocks)
const ballG=new THREE.Group(),ball=sphere(.36,C.butter);ball.position.y=.4;ballG.add(ball);addToy('ball','软球','○',new THREE.Vector3(2,.05,.7),ballG)
const jellyG=new THREE.Group(),jelly=sphere(.58,C.pink);jelly.position.y=.62;jellyG.add(jelly);addToy('jelly','果冻','●',new THREE.Vector3(.5,.05,3.5),jellyG)
const trainG=new THREE.Group();const train=box(1,.38,.48,C.coral),cab=box(.42,.45,.44,C.sky);cab.position.set(.2,.38,0);trainG.add(train,cab);addToy('train','小火车','▰',new THREE.Vector3(2.9,.25,-2.25),trainG)
const musicG=new THREE.Group();[C.coral,C.butter,C.mint,C.sky,C.lavender].forEach((c,i)=>{const bar=box(.25,.08,.7-i*.06,c);bar.position.set((i-2)*.28,.1,0);musicG.add(bar)});addToy('music','木琴','♫',new THREE.Vector3(.7,.08,-2.7),musicG)
const booksG=new THREE.Group();[C.sky,C.peach,C.mint].forEach((c,i)=>{const b=box(.75,.08,.55,c);b.position.set(0,.08+i*.1,0);booksG.add(b)});addToy('books','绘本','▤',new THREE.Vector3(4.1,.08,-3.55),booksG)
const castleToy:{key:string;label:string;emoji:string;position:THREE.Vector3;group:THREE.Group}={key:'castle',label:'城堡',emoji:'♜',position:new THREE.Vector3(-3.2,.1,-2.45),group:castle};toys.unshift(castleToy)

type Needs={play:number;social:number;rest:number;curiosity:number}
type Agent={name:string;group:THREE.Group;target:THREE.Vector3;needs:Needs;activity:string;toy:string|null;speed:number;busyUntil:number;phase:number;lastToy:string|null}
function makeAgent(name:string,color:number,start:THREE.Vector3,phase:number):Agent{const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.65,5,10),mat(color)),head=sphere(.38,0xf4c7a1),hair=new THREE.Mesh(new THREE.SphereGeometry(.39,20,12,0,Math.PI*2,0,Math.PI*.52),mat(C.dark));body.position.y=.73;head.position.y=1.45;hair.position.set(0,1.55,-.04);const eyeMat=new THREE.MeshBasicMaterial({color:0x493b35});for(const x of[-.12,.12]){const e=new THREE.Mesh(new THREE.SphereGeometry(.025,8,6),eyeMat);e.position.set(x,1.48,.35);g.add(e)}g.add(body,head,hair);g.position.copy(start);world.add(g);return{name,group:g,target:start.clone(),needs:{play:.48+phase*.07,social:.42+phase*.1,rest:.2,curiosity:.55-phase*.05},activity:'观察房间',toy:null,speed:1.15,busyUntil:0,phase,lastToy:null}}
const agents=[makeAgent('陶陶',C.mint,new THREE.Vector3(-.8,.05,.6),0),makeAgent('沫沫',C.peach,new THREE.Vector3(1,.05,1.2),1)],strategy=createStrategy();let selected=0,paused=false,night=false,lastPlan=0,toastTimer=0
const preferences:Record<string,[number,number]>={castle:[1,.62],blocks:[.8,.88],ball:[.86,.78],jelly:[.58,.95],train:[.96,.5],music:[.52,1],books:[.42,.98]}
function toyScore(a:Agent,t:Toy){const f:StrategyFeatures={play:a.needs.play,curiosity:a.needs.curiosity,preference:preferences[t.key]?.[agents.indexOf(a)]??.6,satisfaction:.55,novelty:a.lastToy===t.key?.25:.9,repeat:a.lastToy===t.key?.85:.08};return toyStrategyScore(strategy,f)}
function sendToToy(a:Agent,key:string,manual=false){const t=toys.find(x=>x.key===key);if(!t)return;a.target.copy(t.position).add(new THREE.Vector3(.65*(a.phase?1:-1),0,.45));a.activity=`去玩${t.label}`;a.toy=key;a.busyUntil=0;if(manual)show(`${a.name} 去玩 ${t.label}`);renderBrain()}
function plan(a:Agent,now:number){if(now<a.busyUntil)return;if(a.needs.rest>.78){a.target.set(3.3,.05,2.1);a.activity='去沙发休息';a.toy=null;return}const socialF:StrategyFeatures={social:a.needs.social,play:a.needs.play,preference:.8,satisfaction:.55,repeat:.1,isTag:a.needs.play>.65?1:0},socialScore=socialStrategyScore(strategy,socialF);if(socialScore>62&&a.needs.social>.63){const other=agents.find(x=>x!==a)!;a.target.copy(other.group.position).add(new THREE.Vector3(a.phase?.65:-.65,0,.2));a.activity='去找伙伴';a.toy=null;return}const best=[...toys].sort((x,y)=>toyScore(a,y)-toyScore(a,x))[0];sendToToy(a,best.key)}
function arrive(a:Agent,now:number){if(a.busyUntil>now)return;a.busyUntil=now+2200;if(a.toy){const t=toys.find(x=>x.key===a.toy)!;a.activity=`正在玩${t.label}`;a.needs.play=clamp01(a.needs.play-.34);a.needs.curiosity=clamp01(a.needs.curiosity-.28);a.lastToy=a.toy;if(a.toy==='ball')ball.rotation.x+=.8}else if(a.target.x>2.8&&a.target.z>1.5){a.activity='在沙发休息';a.needs.rest=clamp01(a.needs.rest-.62)}else{a.activity='和伙伴互动';a.needs.social=clamp01(a.needs.social-.45);a.needs.play=clamp01(a.needs.play-.12)}renderBrain()}
function renderBrain(){brain.innerHTML=`<div class="brain-title"><b>角色状态</b><span>V16 策略评分 · 点击角色切换</span></div><div class="agent-list">${agents.map((a,i)=>`<button class="agent-card ${selected===i?'active':''}" data-agent="${i}"><div class="agent-head"><b>${a.name}</b><span>${a.activity}</span></div>${(['play','social','rest','curiosity'] as const).map(k=>`<div class="need"><span>${{play:'玩耍',social:'社交',rest:'疲劳',curiosity:'好奇'}[k]}</span><div class="bar"><i style="width:${Math.round(a.needs[k]*100)}%"></i></div><em>${Math.round(a.needs[k]*100)}</em></div>`).join('')}</button>`).join('')}</div><div class="world-state">当前控制：<b>${agents[selected].name}</b> · 点击左下玩具可直接派它过去。两个角色暂停关闭时会自己选活动。<br>策略版本：Champion v${strategy.policyRegistry.currentVersion} · ${strategy.policyRegistry.last.status==='stable'?'稳定':'观察中'} · 回滚 ${strategy.policyRegistry.rollbacks}</div>`;brain.querySelectorAll<HTMLButtonElement>('[data-agent]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.agent);renderBrain()})}
function renderToys(){toyGrid.innerHTML=toys.map(t=>`<button data-toy="${t.key}"><i>${t.emoji}</i><b>${t.label}</b></button>`).join('');toyGrid.querySelectorAll<HTMLButtonElement>('[data-toy]').forEach(b=>b.onclick=()=>sendToToy(agents[selected],b.dataset.toy!,true))}
function show(text:string){toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toast.classList.remove('show'),1300)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}window.addEventListener('resize',resize)
cinema.onclick=()=>{controls.autoRotate=!controls.autoRotate;cinema.classList.toggle('active',controls.autoRotate);show(controls.autoRotate?'电影镜头开启':'电影镜头关闭')}
day.onclick=()=>{night=!night;document.documentElement.classList.toggle('night',night);scene.background=new THREE.Color(night?0x293445:0xf0e4cf);scene.fog=new THREE.Fog(night?0x293445:0xf0e4cf,17,33);hemi.intensity=night?.9:2.5;sun.intensity=night?1.1:3.8;day.textContent=night?'☾':'☀︎'}
pause.onclick=()=>{paused=!paused;pause.classList.toggle('active',paused);pause.textContent=paused?'▶':'Ⅱ';status.textContent=paused?'自主行动已暂停，仍可手动点玩具':'两个角色会根据需要自主选择玩具、社交和休息'}
reset.onclick=()=>{camera.position.copy(cameraHome);controls.target.set(0,1,0);controls.update();show('镜头已复位')}
renderToys();renderBrain();status.textContent='两个角色会根据需要自主选择玩具、社交和休息';document.querySelector('#playBoot')?.remove();document.documentElement.dataset.playReady='true'
const clock=new THREE.Clock();function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04),now=performance.now();controls.update();if(!paused){for(const a of agents){a.needs.play=clamp01(a.needs.play+dt*.018);a.needs.social=clamp01(a.needs.social+dt*.012);a.needs.rest=clamp01(a.needs.rest+dt*.009);a.needs.curiosity=clamp01(a.needs.curiosity+dt*.013);if(now-lastPlan>2600&&now>a.busyUntil)plan(a,now);const delta=a.target.clone().sub(a.group.position);delta.y=0;const d=delta.length();if(d>.12){delta.normalize();a.group.position.addScaledVector(delta,Math.min(d,a.speed*dt));a.group.rotation.y=Math.atan2(delta.x,delta.z);a.group.position.y=.05+Math.abs(Math.sin(now*.008+a.phase))*0.035}else arrive(a,now)}if(now-lastPlan>2600){lastPlan=now;renderBrain()}}ball.rotation.x+=dt*.7;trainG.rotation.y=Math.sin(now*.001)*.18;jelly.scale.setScalar(1+Math.sin(now*.004)*.045);musicG.rotation.y=Math.sin(now*.0015)*.08;renderer.render(scene,camera)}frame()
