export type StrategyWeights={toyPlay:number;toyCuriosity:number;toyPreference:number;toySatisfaction:number;toyNovelty:number;toyRepeat:number;socialNeed:number;socialPlay:number;socialPreference:number;socialSatisfaction:number;socialRepeat:number;socialThreshold:number;restThreshold:number}
export type DecisionKind='toy'|'social'|'rest'
export type StrategyFeatures={play?:number;curiosity?:number;preference?:number;satisfaction?:number;novelty?:number;repeat?:number;social?:number;rest?:number;isTag?:number}
export type DecisionCandidate={kind:DecisionKind;actor:string;key:string;label:string;features:StrategyFeatures;championScore:number}
export type DecisionTrace={id:string;kind:DecisionKind;actor:string;key:string;label:string;score:number;features:StrategyFeatures;reason:string;participants:number;rewards:number[];createdAt:number;settled:boolean;candidates:DecisionCandidate[]}
export type StrategyHistory={label:string;reward:number;kind:DecisionKind;at:number}
export type ReplaySample={id:string;kind:DecisionKind;actor:string;key:string;label:string;features:StrategyFeatures;reward:number;at:number;candidates:DecisionCandidate[]}
export type ReflectionResult={status:'collecting'|'accepted'|'rejected';sampleCount:number;currentLoss:number;candidateLoss:number;improvement:number;changed:string[];reason:string;at:number}
export type ReflectionState={buffer:ReplaySample[];cycles:number;accepted:number;rejected:number;last:ReflectionResult}
export type ShadowSample={id:string;kind:DecisionKind;label:string;reward:number;championPrediction:number;challengerPrediction:number;championError:number;challengerError:number;winner:'champion'|'challenger'|'tie';at:number}
export type ShadowResult={status:'idle'|'shadowing'|'promoted'|'rejected';evaluated:number;challengerWins:number;championWins:number;ties:number;championLoss:number;challengerLoss:number;improvement:number;reason:string;at:number}
export type ShadowState={challenger:StrategyWeights|null;sourceCycle:number;samples:ShadowSample[];promoted:number;rejected:number;last:ShadowResult}
export type ActionValueStat={count:number;avgReward:number}
export type DecisionShadowSample={id:string;championKey:string;championLabel:string;challengerKey:string;challengerLabel:string;agreed:boolean;supported:boolean;actualReward:number;challengerEstimatedReward:number;estimatedGain:number;confidence:number;at:number}
export type DecisionShadowResult={status:'idle'|'shadowing'|'promoted'|'rejected';evaluated:number;agreements:number;divergences:number;supportedDivergences:number;avgEstimatedGain:number;reason:string;at:number}
export type DecisionShadowState={samples:DecisionShadowSample[];actionValues:Record<string,ActionValueStat>;last:DecisionShadowResult}
export type StrategyState={weights:StrategyWeights;updates:number;avgReward:number;lastReward:number;lastDecision:string;history:StrategyHistory[];reflection:ReflectionState;shadow:ShadowState;decisionShadow:DecisionShadowState}

export const BASE_STRATEGY:StrategyWeights={toyPlay:40,toyCuriosity:34,toyPreference:31,toySatisfaction:10,toyNovelty:12,toyRepeat:40,socialNeed:57,socialPlay:30,socialPreference:18,socialSatisfaction:8,socialRepeat:40,socialThreshold:62,restThreshold:67}
const BOUNDS:Record<keyof StrategyWeights,[number,number]>={toyPlay:[20,60],toyCuriosity:[15,55],toyPreference:[12,48],toySatisfaction:[2,24],toyNovelty:[3,24],toyRepeat:[15,60],socialNeed:[30,75],socialPlay:[5,45],socialPreference:[5,35],socialSatisfaction:[1,20],socialRepeat:[15,60],socialThreshold:[50,75],restThreshold:[58,78]}
const REFLECT_EVERY=8,BUFFER_LIMIT=32,MIN_OFFLINE_IMPROVEMENT=.004,MAX_CHANGED=8,SHADOW_EVERY=10,MIN_SHADOW_IMPROVEMENT=.003,MIN_CHALLENGER_WINS=6,MIN_DECISION_DIVERGENCES=2,MIN_SUPPORTED_DIVERGENCES=2,MIN_COUNTERFACTUAL_GAIN=.01
const clamp=(v:number,[lo,hi]:[number,number])=>Math.min(hi,Math.max(lo,v))
const finite=(v:unknown,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?v:fallback
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?Math.min(1,Math.max(0,v)):0
const sigmoid=(x:number)=>1/(1+Math.exp(-x))
function blankReflection():ReflectionState{return{buffer:[],cycles:0,accepted:0,rejected:0,last:{status:'collecting',sampleCount:0,currentLoss:0,candidateLoss:0,improvement:0,changed:[],reason:`正在收集真实决策，累计 ${REFLECT_EVERY} 条后生成 Challenger`,at:Date.now()}}}
function blankShadow():ShadowState{return{challenger:null,sourceCycle:0,samples:[],promoted:0,rejected:0,last:{status:'idle',evaluated:0,challengerWins:0,championWins:0,ties:0,championLoss:0,challengerLoss:0,improvement:0,reason:'暂无 Challenger，先完成离线反思门',at:Date.now()}}}
function blankDecisionShadow():DecisionShadowState{return{samples:[],actionValues:{},last:{status:'idle',evaluated:0,agreements:0,divergences:0,supportedDivergences:0,avgEstimatedGain:0,reason:'暂无策略决策影子样本',at:Date.now()}}}
export function createStrategy(raw?:Partial<StrategyState>|null):StrategyState{
  const weights={...BASE_STRATEGY},incoming=raw?.weights as Partial<StrategyWeights>|undefined
  if(incoming)for(const key of Object.keys(BASE_STRATEGY)as Array<keyof StrategyWeights>)weights[key]=clamp(finite(incoming[key],BASE_STRATEGY[key]),BOUNDS[key])
  const reflection=blankReflection(),r=raw?.reflection
  if(r){reflection.buffer=Array.isArray(r.buffer)?r.buffer.slice(-BUFFER_LIMIT):[];reflection.cycles=Math.max(0,Math.floor(finite(r.cycles,0)));reflection.accepted=Math.max(0,Math.floor(finite(r.accepted,0)));reflection.rejected=Math.max(0,Math.floor(finite(r.rejected,0)));if(r.last&&typeof r.last==='object')reflection.last={...reflection.last,...r.last,changed:Array.isArray(r.last.changed)?r.last.changed.slice(0,MAX_CHANGED):[]}}
  const shadow=blankShadow(),sh=raw?.shadow
  if(sh){const c=sh.challenger as Partial<StrategyWeights>|null|undefined;if(c){const challenger={...weights};for(const key of Object.keys(BASE_STRATEGY)as Array<keyof StrategyWeights>)challenger[key]=clamp(finite(c[key],weights[key]),BOUNDS[key]);shadow.challenger=challenger}shadow.sourceCycle=Math.max(0,Math.floor(finite(sh.sourceCycle,0)));shadow.samples=Array.isArray(sh.samples)?sh.samples.slice(-SHADOW_EVERY):[];shadow.promoted=Math.max(0,Math.floor(finite(sh.promoted,0)));shadow.rejected=Math.max(0,Math.floor(finite(sh.rejected,0)));if(sh.last&&typeof sh.last==='object')shadow.last={...shadow.last,...sh.last}}
  const decisionShadow=blankDecisionShadow(),ds=raw?.decisionShadow
  if(ds){decisionShadow.samples=Array.isArray(ds.samples)?ds.samples.slice(-SHADOW_EVERY):[];decisionShadow.actionValues=ds.actionValues&&typeof ds.actionValues==='object'?ds.actionValues:{};if(ds.last&&typeof ds.last==='object')decisionShadow.last={...decisionShadow.last,...ds.last}}
  return{weights,updates:Math.max(0,Math.floor(finite(raw?.updates,0))),avgReward:clamp(finite(raw?.avgReward,.5),[0,1]),lastReward:clamp(finite(raw?.lastReward,.5),[0,1]),lastDecision:typeof raw?.lastDecision==='string'?raw.lastDecision:'尚未生成 Challenger',history:Array.isArray(raw?.history)?raw!.history!.slice(0,8):[],reflection,shadow,decisionShadow}
}
function toyScore(w:StrategyWeights,f:StrategyFeatures){return n(f.play)*w.toyPlay+n(f.curiosity)*w.toyCuriosity+n(f.preference)*w.toyPreference+n(f.satisfaction)*w.toySatisfaction+n(f.novelty)*w.toyNovelty-n(f.repeat)*w.toyRepeat}
function socialScore(w:StrategyWeights,f:StrategyFeatures){const playWeight=n(f.isTag)?w.socialPlay:w.socialPlay*.34;return n(f.social)*w.socialNeed+n(f.play)*playWeight+n(f.preference)*w.socialPreference+n(f.satisfaction)*w.socialSatisfaction-n(f.repeat)*w.socialRepeat}
function scoreCandidate(w:StrategyWeights,c:DecisionCandidate){if(c.kind==='toy')return toyScore(w,c.features);if(c.kind==='social')return socialScore(w,c.features);return n(c.features.rest)*100}
type ScoreCall={features:StrategyFeatures;score:number;at:number}
type RuntimeScores={toy:ScoreCall[];social:ScoreCall[]}
const runtimeScores=new WeakMap<StrategyState,RuntimeScores>()
function runtimeFor(s:StrategyState){let r=runtimeScores.get(s);if(!r){r={toy:[],social:[]};runtimeScores.set(s,r)}return r}
function pushCall(list:ScoreCall[],features:StrategyFeatures,score:number,limit:number){list.push({features:{...features},score,at:performance.now()});if(list.length>limit)list.splice(0,list.length-limit)}
function fresh(list:ScoreCall[],ms=180){const now=performance.now();return list.filter(x=>now-x.at<=ms)}
export function toyStrategyScore(s:StrategyState,f:Required<Pick<StrategyFeatures,'play'|'curiosity'|'preference'|'satisfaction'|'novelty'|'repeat'>>){const score=toyScore(s.weights,f);pushCall(runtimeFor(s).toy,f,score,8);return score}
export function socialStrategyScore(s:StrategyState,f:Required<Pick<StrategyFeatures,'social'|'play'|'preference'|'satisfaction'|'repeat'|'isTag'>>){const score=socialScore(s.weights,f);pushCall(runtimeFor(s).social,f,score,6);return score}
const socialDefs=[{key:'social:pass',label:'传球'},{key:'social:tag',label:'追逐'},{key:'social:wave',label:'招手'}]
const taoToyDefs=[{key:'castle',label:'城堡滑梯'},{key:'jelly',label:'果冻'},{key:'train',label:'小火车'},{key:'music',label:'木琴'},{key:'books',label:'绘本'}]
const momoToyDefs=[{key:'jelly',label:'果冻'},{key:'train',label:'小火车'},{key:'music',label:'木琴'},{key:'books',label:'绘本'}]
function inferCandidates(s:StrategyState,kind:DecisionKind,actor:string,key:string,label:string,score:number,features:StrategyFeatures){
  const r=runtimeFor(s),out:DecisionCandidate[]=[]
  if(kind!=='rest'){
    const socials=fresh(r.social).slice(-3);if(socials.length===3)socials.forEach((x,i)=>out.push({kind:'social',actor:'双人',key:socialDefs[i].key,label:socialDefs[i].label,features:{...x.features},championScore:x.score}))
  }
  if(kind==='toy'){
    const defs=actor==='陶陶'?taoToyDefs:momoToyDefs,calls=fresh(r.toy).slice(-defs.length);if(calls.length===defs.length)calls.forEach((x,i)=>out.push({kind:'toy',actor,key:defs[i].key,label:defs[i].label,features:{...x.features},championScore:x.score}))
  }
  if(kind==='rest')out.push({kind:'rest',actor,key,label,features:{...features},championScore:score})
  if(!out.some(x=>x.key===key&&x.actor===actor))out.push({kind,actor,key,label,features:{...features},championScore:score})
  r.social=[];r.toy=[];return out
}
export function makeDecision(kind:DecisionKind,actor:string,key:string,label:string,score:number,features:StrategyFeatures,reason:string,participants=1):DecisionTrace{return{id:`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,kind,actor,key,label,score,features,reason,participants,rewards:[],createdAt:Date.now(),settled:false,candidates:inferCandidates(currentStrategyForInference,kind,actor,key,label,score,features)}}
let currentStrategyForInference:StrategyState
const originalCreate=createStrategy
export function bindStrategyForInference(s:StrategyState){currentStrategyForInference=s;return s}
function predict(w:StrategyWeights,s:ReplaySample){if(s.kind==='toy')return sigmoid((toyScore(w,s.features)-42)/18);if(s.kind==='social')return sigmoid((socialScore(w,s.features)-w.socialThreshold)/13);return sigmoid((n(s.features.rest)*100-w.restThreshold)/7)}
function loss(w:StrategyWeights,samples:ReplaySample[]){if(!samples.length)return 1;let total=0;for(const s of samples){const e=predict(w,s)-s.reward;total+=e*e}let regularize=0;for(const k of Object.keys(BASE_STRATEGY)as Array<keyof StrategyWeights>){const span=BOUNDS[k][1]-BOUNDS[k][0],d=(w[k]-BASE_STRATEGY[k])/span;regularize+=d*d}return total/samples.length+regularize*.012}
function bounded(w:StrategyWeights,key:keyof StrategyWeights,v:number){w[key]=clamp(v,BOUNDS[key])}
function candidateFrom(current:StrategyWeights,samples:ReplaySample[],cycles:number){const w={...current},scale=Math.max(.22,.75/Math.sqrt(1+cycles*.35));for(const s of samples){const a=s.reward-.55,f=s.features;if(s.kind==='toy'){bounded(w,'toyPlay',w.toyPlay+scale*a*n(f.play));bounded(w,'toyCuriosity',w.toyCuriosity+scale*a*n(f.curiosity));bounded(w,'toyPreference',w.toyPreference+scale*a*n(f.preference));bounded(w,'toySatisfaction',w.toySatisfaction+scale*a*n(f.satisfaction));bounded(w,'toyNovelty',w.toyNovelty+scale*a*n(f.novelty));bounded(w,'toyRepeat',w.toyRepeat-scale*a*n(f.repeat))}else if(s.kind==='social'){bounded(w,'socialNeed',w.socialNeed+scale*a*n(f.social));bounded(w,'socialPlay',w.socialPlay+scale*a*n(f.play)*(.35+.65*n(f.isTag)));bounded(w,'socialPreference',w.socialPreference+scale*a*n(f.preference));bounded(w,'socialSatisfaction',w.socialSatisfaction+scale*a*n(f.satisfaction));bounded(w,'socialRepeat',w.socialRepeat-scale*a*n(f.repeat));bounded(w,'socialThreshold',w.socialThreshold-scale*a*.45)}else bounded(w,'restThreshold',w.restThreshold-scale*a*.6)}for(const k of Object.keys(BASE_STRATEGY)as Array<keyof StrategyWeights>){w[k]+=(BASE_STRATEGY[k]-w[k])*.014;bounded(w,k,w[k])}return w}
function diffKeys(a:StrategyWeights,b:StrategyWeights){return(Object.keys(a)as Array<keyof StrategyWeights>).filter(k=>Math.abs(a[k]-b[k])>.025).sort((x,y)=>Math.abs(b[y]-a[y])-Math.abs(b[x]-a[x])).slice(0,MAX_CHANGED)}
function launchChallenger(s:StrategyState){
  if(s.shadow.challenger)return false
  const batch=s.reflection.buffer.slice(-REFLECT_EVERY);if(batch.length<REFLECT_EVERY)return false
  s.reflection.cycles+=1
  const proposal=batch.filter((_,i)=>i%2===0),evaluation=batch.filter((_,i)=>i%2===1),candidate=candidateFrom(s.weights,proposal,s.reflection.cycles),currentLoss=loss(s.weights,evaluation),candidateLoss=loss(candidate,evaluation),improvement=currentLoss-candidateLoss,changed=diffKeys(s.weights,candidate),kinds=new Set(batch.map(x=>x.kind)).size,evalKinds=new Set(evaluation.map(x=>x.kind)).size
  let accept=improvement>MIN_OFFLINE_IMPROVEMENT&&changed.length>0&&kinds>=2&&evalKinds>=2,reason=''
  if(kinds<2){accept=false;reason='整批样本类型过于单一，拒绝生成 Challenger'}else if(evalKinds<2){accept=false;reason='留出评估集覆盖不足，拒绝生成 Challenger'}else if(changed.length===0){accept=false;reason='候选与 Champion 几乎一致，无需进入影子模式'}else if(improvement<=MIN_OFFLINE_IMPROVEMENT){accept=false;reason=`离线留出提升不足 ${(improvement*100).toFixed(2)}%，Champion 保持不变`}else reason=`离线门通过 ${(improvement*100).toFixed(2)}%，Challenger 进入影子模式`
  if(accept){s.shadow.challenger=candidate;s.shadow.sourceCycle=s.reflection.cycles;s.shadow.samples=[];s.decisionShadow.samples=[];s.decisionShadow.last={status:'shadowing',evaluated:0,agreements:0,divergences:0,supportedDivergences:0,avgEstimatedGain:0,reason:`Challenger #${s.reflection.cycles} 开始策略决策影子`,at:Date.now()};s.shadow.last={status:'shadowing',evaluated:0,challengerWins:0,championWins:0,ties:0,championLoss:0,challengerLoss:0,improvement:0,reason:`Challenger #${s.reflection.cycles} 影子运行 0/${SHADOW_EVERY}`,at:Date.now()};s.reflection.accepted+=1;s.lastDecision=`Challenger #${s.reflection.cycles} 已进入双重影子模式`}
  else{s.reflection.rejected+=1;s.lastDecision=`反思 #${s.reflection.cycles} 拒绝 · ${reason}`}
  s.reflection.last={status:accept?'accepted':'rejected',sampleCount:batch.length,currentLoss,candidateLoss,improvement,changed,reason,at:Date.now()};s.reflection.buffer=s.reflection.buffer.slice(-Math.floor(REFLECT_EVERY/2));return accept
}
function choiceWithWeights(w:StrategyWeights,candidates:DecisionCandidate[]){
  const rest=candidates.filter(x=>x.kind==='rest').sort((a,b)=>n(b.features.rest)-n(a.features.rest))[0];if(rest&&n(rest.features.rest)*100>w.restThreshold)return{key:rest.key,label:rest.label,candidate:rest}
  const socials=candidates.filter(x=>x.kind==='social').map(c=>({c,score:socialScore(w,c.features)})).sort((a,b)=>b.score-a.score);if(socials[0]&&socials[0].score>w.socialThreshold)return{key:socials[0].c.key,label:socials[0].c.label,candidate:socials[0].c}
  const toys=candidates.filter(x=>x.kind==='toy').map(c=>({c,score:toyScore(w,c.features)})).sort((a,b)=>b.score-a.score);if(toys[0])return{key:toys[0].c.key,label:toys[0].c.label,candidate:toys[0].c}
  return{key:'fallback:continue',label:'继续探索',candidate:null as DecisionCandidate|null}
}
function estimateAlternative(s:StrategyState,key:string){const stat=s.decisionShadow.actionValues[key];if(!stat||stat.count<2)return{value:s.avgReward,confidence:0,supported:false};const value=(stat.avgReward*stat.count+s.avgReward*2)/(stat.count+2);return{value,confidence:Math.min(1,stat.count/6),supported:true}}
function updateActionValue(s:StrategyState,key:string,reward:number){const old=s.decisionShadow.actionValues[key],count=(old?.count??0)+1,avg=((old?.avgReward??0)*(count-1)+reward)/count;s.decisionShadow.actionValues[key]={count,avgReward:avg}}
function evaluateDecisionShadow(s:StrategyState,sample:ReplaySample,challenger:StrategyWeights){const choice=choiceWithWeights(challenger,sample.candidates),agreed=choice.key===sample.key,est=agreed?{value:sample.reward,confidence:1,supported:true}:estimateAlternative(s,choice.key),gain=est.value-sample.reward,entry:DecisionShadowSample={id:sample.id,championKey:sample.key,championLabel:sample.label,challengerKey:choice.key,challengerLabel:choice.label,agreed,supported:agreed||est.supported,actualReward:sample.reward,challengerEstimatedReward:est.value,estimatedGain:agreed?0:gain,confidence:est.confidence,at:Date.now()};s.decisionShadow.samples.push(entry);s.decisionShadow.samples=s.decisionShadow.samples.slice(-SHADOW_EVERY);const samples=s.decisionShadow.samples,agreements=samples.filter(x=>x.agreed).length,div=samples.length-agreements,supported=samples.filter(x=>!x.agreed&&x.supported).length,supportedSamples=samples.filter(x=>!x.agreed&&x.supported),avgGain=supportedSamples.length?supportedSamples.reduce((a,b)=>a+b.estimatedGain*b.confidence,0)/Math.max(.001,supportedSamples.reduce((a,b)=>a+b.confidence,0)):0;s.decisionShadow.last={status:'shadowing',evaluated:samples.length,agreements,divergences:div,supportedDivergences:supported,avgEstimatedGain:avgGain,reason:`策略决策对照 ${samples.length}/${SHADOW_EVERY} · 一致 ${agreements} · 分歧 ${div} · 有证据分歧 ${supported}`,at:Date.now()};return s.decisionShadow.last}
function finishShadow(s:StrategyState,predictionGate:boolean,predictionReason:string){const d=s.decisionShadow.last,decisionGate=d.divergences>=MIN_DECISION_DIVERGENCES&&d.supportedDivergences>=MIN_SUPPORTED_DIVERGENCES&&d.avgEstimatedGain>MIN_COUNTERFACTUAL_GAIN;let decisionReason='';if(d.divergences<MIN_DECISION_DIVERGENCES)decisionReason=`Challenger 与 Champion 的 Top-1 决策几乎一致（仅 ${d.divergences} 次分歧）`;else if(d.supportedDivergences<MIN_SUPPORTED_DIVERGENCES)decisionReason=`替代动作真实历史证据不足（${d.supportedDivergences}/${MIN_SUPPORTED_DIVERGENCES}）`;else if(d.avgEstimatedGain<=MIN_COUNTERFACTUAL_GAIN)decisionReason=`替代动作反事实估计增益不足 ${(d.avgEstimatedGain*100).toFixed(2)}%`;else decisionReason=`策略决策影子通过：有证据替代动作平均估计增益 ${(d.avgEstimatedGain*100).toFixed(2)}%`
  return{pass:predictionGate&&decisionGate,reason:predictionGate?decisionReason:predictionReason,decisionReason}
}
function evaluateShadow(s:StrategyState,sample:ReplaySample){const challenger=s.shadow.challenger;if(!challenger)return false;const cp=predict(s.weights,sample),xp=predict(challenger,sample),ce=(cp-sample.reward)**2,xe=(xp-sample.reward)**2,winner=xe+.0004<ce?'challenger':ce+.0004<xe?'champion':'tie';s.shadow.samples.push({id:sample.id,kind:sample.kind,label:sample.label,reward:sample.reward,championPrediction:cp,challengerPrediction:xp,championError:ce,challengerError:xe,winner,at:Date.now()});s.shadow.samples=s.shadow.samples.slice(-SHADOW_EVERY);evaluateDecisionShadow(s,sample,challenger);const samples=s.shadow.samples,cw=samples.filter(x=>x.winner==='challenger').length,pw=samples.filter(x=>x.winner==='champion').length,ties=samples.length-cw-pw,cl=samples.reduce((a,b)=>a+b.championError,0)/samples.length,xl=samples.reduce((a,b)=>a+b.challengerError,0)/samples.length,improvement=cl-xl,kinds=new Set(samples.map(x=>x.kind)).size;s.shadow.last={status:'shadowing',evaluated:samples.length,challengerWins:cw,championWins:pw,ties,championLoss:cl,challengerLoss:xl,improvement,reason:`价值影子 ${samples.length}/${SHADOW_EVERY} · Challenger ${cw} 胜 / Champion ${pw} 胜`,at:Date.now()};if(samples.length<SHADOW_EVERY)return false
  const predictionGate=improvement>MIN_SHADOW_IMPROVEMENT&&cw>=MIN_CHALLENGER_WINS&&kinds>=2;let predictionReason='';if(kinds<2)predictionReason='价值影子样本类型覆盖不足';else if(cw<MIN_CHALLENGER_WINS)predictionReason=`价值预测胜场不足 ${cw}/${SHADOW_EVERY}`;else predictionReason=`价值预测误差改善不足 ${(improvement*100).toFixed(2)}%`;const final=finishShadow(s,predictionGate,predictionReason)
  if(final.pass){s.weights={...challenger};s.updates+=1;s.shadow.promoted+=1;s.shadow.last={...s.shadow.last,status:'promoted',reason:`双重影子通过：价值预测 + 策略决策均优于 Champion`};s.decisionShadow.last={...s.decisionShadow.last,status:'promoted',reason:final.decisionReason};s.lastDecision=`Challenger #${s.shadow.sourceCycle} 晋升为新 Champion`}
  else{s.shadow.rejected+=1;s.shadow.last={...s.shadow.last,status:'rejected',reason:`Challenger 未晋升：${final.reason}`};s.decisionShadow.last={...s.decisionShadow.last,status:'rejected',reason:final.reason};s.lastDecision=`Challenger #${s.shadow.sourceCycle} 双重影子未通过，继续保留 Champion`}
  s.shadow.challenger=null;s.shadow.samples=[];s.decisionShadow.samples=[];s.reflection.buffer=[];return final.pass
}
export function reportDecisionReward(s:StrategyState,t:DecisionTrace|undefined|null,reward:number){if(!t||t.settled)return false;t.rewards.push(clamp(reward,[0,1]));if(t.rewards.length<t.participants)return false;t.settled=true;const avg=t.rewards.reduce((a,b)=>a+b,0)/t.rewards.length,sample:ReplaySample={id:t.id,kind:t.kind,actor:t.actor,key:t.key,label:t.label,features:{...t.features},reward:avg,at:Date.now(),candidates:Array.isArray(t.candidates)?t.candidates.map(x=>({...x,features:{...x.features}})):[]};s.lastReward=avg;const total=s.history.length+1;s.avgReward=(s.avgReward*Math.min(20,total-1)+avg)/Math.min(21,total);s.history.unshift({label:t.label,reward:avg,kind:t.kind,at:Date.now()});s.history=s.history.slice(0,8)
  let changed=false;if(s.shadow.challenger)changed=evaluateShadow(s,sample);else{s.reflection.buffer.push(sample);s.reflection.buffer=s.reflection.buffer.slice(-BUFFER_LIMIT);s.lastDecision=`Champion 已记录 ${t.actor} · ${t.label} · 回报 ${Math.round(avg*100)}% · 反思池 ${s.reflection.buffer.length}/${REFLECT_EVERY}`;if(s.reflection.buffer.length<REFLECT_EVERY)s.reflection.last={status:'collecting',sampleCount:s.reflection.buffer.length,currentLoss:0,candidateLoss:0,improvement:0,changed:[],reason:`收集 Champion 回放 ${s.reflection.buffer.length}/${REFLECT_EVERY}`,at:Date.now()};else changed=launchChallenger(s)}
  updateActionValue(s,t.key,avg);return changed
}
export function strategySummary(s:StrategyState){const w=s.weights,r=s.reflection.last,sh=s.shadow.last,ds=s.decisionShadow.last;return{toy:`玩${w.toyPlay.toFixed(0)} 好奇${w.toyCuriosity.toFixed(0)} 偏好${w.toyPreference.toFixed(0)} 探索${w.toyNovelty.toFixed(0)}`,social:`社交${w.socialNeed.toFixed(0)} 偏好${w.socialPreference.toFixed(0)} 门槛${w.socialThreshold.toFixed(0)}`,rest:`休息门槛 ${w.restThreshold.toFixed(0)}`,reflection:`反思${s.reflection.cycles}次 · 离线通过${s.reflection.accepted} / 拒绝${s.reflection.rejected} · ${r.reason}`,shadow:`影子晋升${s.shadow.promoted} / 淘汰${s.shadow.rejected} · ${sh.reason}`,decisionShadow:`决策影子：一致${ds.agreements} / 分歧${ds.divergences} / 有证据${ds.supportedDivergences} · ${ds.reason}`}}
